=== uo276670/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">
  <xs:element name="circuito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fecha" />
        <xs:element ref="ubicacion" />
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="referencias" />
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="multimedia" />
        <xs:element ref="tramos" />
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
      <xs:attribute name="vueltas" type="xs:integer" use="required" />
      <xs:attribute name="largo" type="xs:decimal" use="required" />
      <xs:attribute name="ancho_medio" type="xs:decimal" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="fecha">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="dia" type="xs:date" use="required" />
          <xs:attribute name="hora" type="xs:time" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="ubicacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coordenadas" />
      </xs:sequence>
      <xs:attribute name="localidad" type="xs:string" use="required" />
      <xs:attribute name="pais" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="coordenadas">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="longitud" type="xs:decimal" use="required" />
          <xs:attribute name="latitud" type="xs:decimal" use="required" />
          <xs:attribute name="altitud" type="xs:decimal" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="contenido" type="xs:string" use="required" />
          <xs:attribute name="url" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="tramos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tramo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coordenadas" />
      </xs:sequence>
      <xs:attribute name="numero" type="xs:integer" use="required" />
      <xs:attribute name="sector" type="xs:integer" use="required" />
      <xs:attribute name="largo" type="xs:decimal" use="required" />
      <xs:attribute name="unidad_medida" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="multimedia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fotografias" />
        <xs:element ref="videos" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fotografias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fotografia">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="url" type="xs:string" use="required" />
          <xs:attribute name="formato" type="xs:string" use="required" />
          <xs:attribute name="texto_alternativo" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="3" ref="video" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="video">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="url" type="xs:string" use="required" />
          <xs:attribute name="formato" type="xs:string" use="required" />
          <xs:attribute name="texto_alternativo" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== uo276670/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito 
    xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
    nombre="Losail" vueltas="22" largo="5.380" ancho_medio="12" >
    <fecha dia="2024-12-01" hora="18:00:00"></fecha>
    <ubicacion localidad="Lusail" pais="Qatar">
        <coordenadas longitud="25.48907386591285" latitud="51.45084416236202" altitud="13"></coordenadas>
    </ubicacion>
    <referencias>
        <referencia 
            contenido="La carrera sera el 1/12 a las 24 horas" 
            url="https://es.motorsport.com/f1/news/horarios-carreras-formula1-2024/10559597/" >
        </referencia>
        <referencia 
            contenido="Información a cerca de las dimensiones y tramos de la pista han sido sacadas de aqui" 
            url="https://en.wikipedia.org/wiki/Qatar_Grand_Prix">
        </referencia>
        <referencia 
            contenido="pagina oficial de la f1" 
            url="https://www.formula1.com/">
        </referencia>
    </referencias>
    <multimedia>
        <fotografias>  
            <fotografia 
                formato="jpg"
                texto_alternativo="Vista cenital del circuito de Qatar Losail"
                url="losail_airview.jpg">
            </fotografia>
            <fotografia 
                formato="png"
                texto_alternativo="Mapa dibujado del recorrido del circuito de Qatar Losail con los diferentes tramos que lo componen"
                url="losail_map.png">
            </fotografia>
            <fotografia 
                formato="jpg"
                texto_alternativo="Imagen del circuito de Qatar Losail desde las gradas cerca de la línea de meta"
                url="losail_stands.jpg">
            </fotografia>
        </fotografias>
        <videos>
            <video            
                formato="mp4"
                texto_alternativo="Video de Max Versaten corriendo en Qtar de 2023"
                url="Max_Verstappen_Pole_ 2023_Qatar.mp4">
            </video>
        </videos>
    </multimedia>
    <tramos>
        <tramo numero="01" sector="1" largo="455.16" unidad_medida="Metros">
            <coordenadas longitud="25.492831" latitud="51.447432" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="02" sector="1" largo="59.23" unidad_medida="Metros">
            <coordenadas longitud="25.493293" latitud="51.447769" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="03" sector="1" largo="51.32" unidad_medida="Metros">
            <coordenadas longitud="25.493351" latitud="51.448291" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="04" sector="1" largo="200.99" unidad_medida="Metros">
            <coordenadas longitud="25.492429" latitud="51.450008" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="05" sector="1" largo="47.46" unidad_medida="Metros">
            <coordenadas longitud="25.492373" latitud="51.450421" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="06" sector="1" largo="45.26" unidad_medida="Metros">
            <coordenadas longitud="25.492885" latitud="51.450672" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="07" sector="1" largo="179.25" unidad_medida="Metros">
            <coordenadas longitud="25.494502" latitud="51.450722" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="08" sector="1" largo="371.04" unidad_medida="Metros">
            <coordenadas longitud="25.496979" latitud="51.453205" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="09" sector="1" largo="50.99" unidad_medida="Metros">
            <coordenadas longitud="25.497105" latitud="51.453697" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="10" sector="1" largo="128.52" unidad_medida="Metros">
            <coordenadas longitud="25.496356" latitud="51.454660" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="11" sector="1" largo="52.62" unidad_medida="Metros">
            <coordenadas longitud="25.495897" latitud="51.454682" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="12" sector="1" largo="121.61" unidad_medida="Metros">
            <coordenadas longitud="25.495081" latitud="51.453878" altitud="13"></coordenadas>
        </tramo>
        
        <tramo numero="13" sector="2" largo="118.44" unidad_medida="Metros">
            <coordenadas longitud="25.494285" latitud="51.453098" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="14" sector="2" largo="28.51" unidad_medida="Metros">
            <coordenadas longitud="25.494023" latitud="51.453114" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="15" sector="2" largo="31.99" unidad_medida="Metros">
            <coordenadas longitud="25.493860" latitud="51.453372" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="16" sector="2" largo="301.88" unidad_medida="Metros">
            <coordenadas longitud="25.494852" latitud="51.456175" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="17" sector="2" largo="41.53" unidad_medida="Metros">
            <coordenadas longitud="25.494831" latitud="51.456588" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="18" sector="2" largo="36.47" unidad_medida="Metros">
            <coordenadas longitud="25.494605" latitud="51.456859" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="19" sector="2" largo="31.22" unidad_medida="Metros">
            <coordenadas longitud="25.494345" latitud="51.456952" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="20" sector="2" largo="45.37" unidad_medida="Metros">
            <coordenadas longitud="25.493957" latitud="51.456824" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="21" sector="2" largo="114.09" unidad_medida="Metros">
            <coordenadas longitud="25.493210" latitud="51.456044" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="22" sector="2" largo="113.94" unidad_medida="Metros">
            <coordenadas longitud="25.492224" latitud="51.455697" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="23" sector="2" largo="53.57" unidad_medida="Metros">
            <coordenadas longitud="25.491842" latitud="51.455380" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="24" sector="2" largo="116.14" unidad_medida="Metros">
            <coordenadas longitud="25.491489" latitud="51.453767" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="25" sector="2" largo="38.34" unidad_medida="Metros">
            <coordenadas longitud="25.491231" latitud="51.453506" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="26" sector="2" largo="36.9" unidad_medida="Metros">
            <coordenadas longitud="25.490899" latitud="51.453568" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="27" sector="2" largo="85.65" unidad_medida="Metros">
            <coordenadas longitud="25.490340" latitud="51.454165" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="28" sector="2" largo="78.74" unidad_medida="Metros">
            <coordenadas longitud="25.490045" latitud="51.454882" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="29" sector="2" largo="96.38" unidad_medida="Metros">
            <coordenadas longitud="25.489762" latitud="51.455785" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="30" sector="2" largo="213.17" unidad_medida="Metros">
            <coordenadas longitud="25.489940" latitud="51.457909" altitud="13"></coordenadas>
        </tramo>
        
        <tramo numero="31" sector="3" largo="79.97" unidad_medida="Metros">
            <coordenadas longitud="25.490004" latitud="51.458701" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="32" sector="3" largo="68.22" unidad_medida="Metros">
            <coordenadas longitud="25.489702" latitud="51.459303" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="33" sector="3" largo="131.48" unidad_medida="Metros">
            <coordenadas longitud="25.488672" latitud="51.459952" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="34" sector="3" largo="38.88" unidad_medida="Metros">
            <coordenadas longitud="25.488319" latitud="51.459949" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="35" sector="3" largo="161.98" unidad_medida="Metros">
            <coordenadas longitud="25.487086" latitud="51.459087" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="36" sector="3" largo="45.77" unidad_medida="Metros">
            <coordenadas longitud="25.486888" latitud="51.458668" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="37" sector="3" largo="280.28" unidad_medida="Metros">
            <coordenadas longitud="25.487319" latitud="51.455919" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="38" sector="3" largo="42.84" unidad_medida="Metros">
            <coordenadas longitud="25.487175" latitud="51.455529" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="39" sector="3" largo="404.09" unidad_medida="Metros">
            <coordenadas longitud="25.483958" latitud="51.453643" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="40" sector="3" largo="43.56" unidad_medida="Metros">
            <coordenadas longitud="25.483794" latitud="51.453254" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="41" sector="3" largo="51.45" unidad_medida="Metros">
            <coordenadas longitud="25.483973" latitud="51.452783" altitud="13"></coordenadas>
        </tramo>
        <tramo numero="42" sector="3" largo="665.17" unidad_medida="Metros">
            <coordenadas longitud="25.489217" latitud="51.449572" altitud="13"></coordenadas>
